### PR TITLE
fix: fix template creation, provide sensible defaults to SVGO

### PR DESCRIPTION
**Pull request by ndrscodes**
fixes a bug which prevented compilation of SVGs with `<style>` tags. Also provides a sensible SVGO default config. 
This also makes it harder to inject code through malicious svg files during compilation.

### CODE REVIEW

**Comment by kwilfert** [comment]
It's a bit hard for me to really understand, what your changes actually do.
So please don't mind if I leave a few comments.

**Comment by kwilfert** [comment]
After looking up a few things like the configuration and such, I beliebe I understand the solution.
It's a bummer though, that there is barely any documentation on such settings apart from a few gh issues and the source code itself.
Anyway, now for the functional test...

**Comment by kwilfert** [comment]
Installing it as dependency into our portal results in 0 vulnerabilites.
My method of installation was the direct path.

The resulting website is blank as it stops loading dude to the following errors:

Uncaught ReferenceError: h is not defined
    at ./src/assets/images/svg/search.svg (search.svg:1:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/components/utility/Icon.vue?vue&type=script&lang=js& (SubHeader.vue:121:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/components/utility/Icon.vue?vue&type=script&lang=js& (SubHeader.vue?cc1f:1:230)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/components/utility/Icon.vue

**Comment by ndrscodes** [comment]
> Installing it as dependency into our portal results in 0 vulnerabilites. My method of installation was the direct path.
> 
> The resulting website is blank as it stops loading due to the following error:
> 
> Uncaught ReferenceError: h is not defined at ./src/assets/images/svg/search.svg (search.svg:1:1) at **webpack_require** (bootstrap:24:1) at fn (hot module replacement:62:1) at ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/components/utility/Icon.vue?vue&type=script&lang=js& (SubHeader.vue:121:1) at **webpack_require** (bootstrap:24:1) at fn (hot module replacement:62:1) at ./src/components/utility/Icon.vue?vue&type=script&lang=js& (SubHeader.vue?cc1f:1:230) at **webpack_require** (bootstrap:24:1) at fn (hot module replacement:62:1) at ./src/components/utility/Icon.vue

check your vue.config.js. vue-loader must be used instead of babel-loader.

**Comment by kwilfert** [comment]
> > Installing it as dependency into our portal results in 0 vulnerabilites. My method of installation was the direct path.
> > The resulting website is blank as it stops loading due to the following error:
> > Uncaught ReferenceError: h is not defined at ./src/assets/images/svg/search.svg (search.svg:1:1) at **webpack_require** (bootstrap:24:1) at fn (hot module replacement:62:1) at ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/components/utility/Icon.vue?vue&type=script&lang=js& (SubHeader.vue:121:1) at **webpack_require** (bootstrap:24:1) at fn (hot module replacement:62:1) at ./src/components/utility/Icon.vue?vue&type=script&lang=js& (SubHeader.vue?cc1f:1:230) at **webpack_require** (bootstrap:24:1) at fn (hot module replacement:62:1) at ./src/components/utility/Icon.vue
> 
> check your vue.config.js. vue-loader must be used instead of babel-loader.

Ah, that's what I was missing. Now it works like a charm. SVGs are displayed correctly, zero vulnerabilities. 
Works like a charm

**Review by kwilfert — APPROVED** [review]
LGTM

**Pull request merged**
